### PR TITLE
refactor: auto controller parameter type overloading

### PR DESCRIPTION
**Pull request by changchanghwang**
## Description

`AutoController` parameter type overloading

## References

https://github.com/nestjs/nest/blob/master/packages/common/decorators/core/controller.decorator.ts

## Checklist

- [x] Add labels and reviewers ?
- [x] Are you fully explaining what you changed ?
- [x] Did you check that there is no conflict with the base branch ?

### CODE REVIEW

**Comment by changchanghwang** [comment]
리뷰어설정이 안됩니다ㅠ

**Comment by hubtwork** [comment]
I’m in out for work, so forwarded to @player31-kks , @Nhahan

**Comment by hubtwork** [comment]
please work based on dev branch. not for main.

**Comment by changchanghwang** [comment]
why dev is default branch not main?

**Comment by Nhahan** [comment]
I've changed it to merge into the dev branch

**Comment by Nhahan** [comment]
We will set it up so that anyone can submit PRs to the 'dev' branch.

**Comment by player31-kks** [comment]
It's really great, and it could be handled neatly by overloading.

**Review by player31-kks — APPROVED** [review]

**Comment by Nhahan** [comment]
I never used typescript overloading like this before. 🥲 I love this PR. He is GOSU. 😄

**Review by Nhahan — APPROVED** [review]

**Pull request merged**
